INSERT INTO person(First_name,  Last_name,Nationality) VALUES 
("Sajeel","Hussain","Pakistan"),
("Hussnain","Medhi","Pakistan"),
("Raja Haider","Ali","Pakistan"),
("Tanzeel","Ur Rehman","Pakistan"),
("Lamees","Zafar","Pakistan"),
("Ramsey", "Aaron ","England"),
('Bernd','Leno','Germany'),
('Matt','Macey','England'),
('Lionel','Messi','Spain'),
('Neymar ','da Silva','Spain'),
('Rúnar','Alex Rúnarsson','Iceland'),
('Héctor','Bellerín','Spain'),
('Kieran','Tierney','Scotland'),
('William','Saliba','France'),
('Rob','Holding','England'),
('Shkodran','Mustafi','Germany'),
('Calum','Chambers','England'),
('David','Luiz','Brazil'),
('Sead','Kolasinac','Bosnia And Herzegovina'),
('Gabriel','Magalhães','Brazil'),
('Mesut','Özil','Germany'),
('Lucas','Torreira','Uruguay'),
('Ainsley','Maitland-Niles','England'),
('Mohamed','Elneny','Egypt'),
('Joseph','Willock','England'),
('Matteo','Guendouzi','France'),
('Emile','Smith Rowe','England'),
('Granit','Xhaka','Switzerland'),
('Bukayo','Saka','England'),
('Dani','Ceballos','Spain'),
('Alexandre','Lacazette','France'),
('Pierre-Emerick','Aubameyang','Gabon'),
('Reiss','Nelson','England'),
('Eddie','Nketiah','England'),
('Tom','Heaton','England'),
('Jed','Steer','England'),
('Lovre','Kalinic','Croatia'),
('Neil','Taylor','Wales'),
('Ezri','Konsa Ngoyo','England'),
('Matt','Targett','England'),
('Ahmed','El Mohamady','Egypt'),
('Kortney','Hause','England'),
('Tyrone','Mings','England'),
('Matthew','Cash','England'),
('Douglas','Luiz','Brazil'),
('John','McGinn','Scotland'),
('Henri','Lansbury','England'),
('Jack','Grealish','England'),
('Marvelous','Nakamba','Zimbabwe'),
('Conor','Hourihane','Ireland'),
('Anwar','El Ghazi','Netherlands'),
('Jacob','Ramsey','England'),
('Keinan','Davis','England'),
('Ollie','Watkins','England'),
('Mat','Ryan','Australia'),
('Jason','Steele','England'),
('Christian','Walton','England'),
('Tariq','Lamptey','England'),
('Lewis','Dunk','England'),
('Adam','Webster','England'),
('Dan','Burn','England'),
('Romaric','Yapi','France'),
('Alex','Cochrane','England'),
('Haydon','Roberts','England'),
('Dale','Stephens','England'),
('Yves','Bissouma','Mali'),
('Alexis','Mac Allister','Argentina'),
('Adam','Lallana','England'),
('Solly','March','England'),
('Steven','Alzate','Colombia'),
('Max','Sanders','England'),
('Jayson','Molumby','Ireland'),
('Lars','Dendoncker','Belgium'),
('Peter','Gwargis','Sweden'),
('Leandro','Trossard','Belgium'),
('Neal','Maupay','France'),
('Alireza','Jahanbakhsh','Iran'),
('Aaron','Connolly','Ireland'),
('Florin','Andone','Romania'),
('Nick','Pope','England'),
('Bailey','Peacock-Farrell','Northern Ireland'),
('Will','Norris','England'),
('Matthew','Lowton','England'),
('Charlie','Taylor','England'),
('James','Tarkowski','England'),
('Ben','Mee','England'),
('Erik','Pieters','Netherlands'),
('Phil','Bardsley','Scotland'),
('Kevin','Long','Ireland'),
('Jimmy','Dunne','Ireland'),
('Bobby','Thomas','England'),
('Anthony','Driscoll Glennon','England'),
('Jack','Cork','England'),
('Josh','Brownhill','England'),
('Dwight','McNeil','England'),
('Robbie','Brady','Ireland'),
('Ashley','Westwood','England'),
('Josh','Benson','England'),
('Chris','Wood','New Zealand'),
('Ashley','Barnes','England'),
('Jay','Rodriguez','England'),
('Matej','Vydra','Czech Republic'),
('Kepa','Arrizabalaga','Spain');